#!/bin/bash


export http_proxy=http://10.250.172.140:3128
export https_proxy=http://10.250.172.140:3128

function main {

	local version=${1:-"v0.2.1"}
	local repo_url=https://github.com/ownport/portable-ansible/releases/download/${version}/portable-ansible-${version}-py2.tar.bz2
		
	if ! curl -fsSL -o "portable-ansible.tar.bz2" "${repo_url}"; then
		fail "failed to download portable-ansible binary from ${repo_url}"
	fi
	
	tar jxvf portable-ansible.tar.bz2 > /dev/null && rm -rf portable-ansible.tar.bz2
	
	ln -s ansible ansible-playbook
}

main $@
