- name: Get flynn install script
  get_url:
    url: https://dl.flynn.io/install-flynn
    dest: /opt/install-flynn
    mode: 0755
  environment: "{{ proxy_env }}"

- name: Check flynn
  shell: flynn-host --version
  ignore_errors: true
  when: not force 
  register: is_flynn_installed

# - name: Check if cluster was deployed
#   shell: curl -I http://dashboard."{{ flynn_cluster_name }}"/
#   ignore_errors: true
#   register: is_flynn_deployed

- name: Install flynn
  shell: bash /opt/install-flynn --clean --yes
  when: is_flynn_installed is failed or force
  environment: "{{ proxy_env }}"

- name: Make sure default rules for iptables FORWARD Chain is ACCEPT
  iptables:
    chain: FORWARD
    policy: ACCEPT
  
- name: Make sure service is stopped
  service:
    name: flynn-host
    state: stopped
    
- name: Backup old bolt state data
  shell: BackupDir=/var/lib/flynn/backup.$(date +%F_%R)/; mkdir ${BackupDir} && mv /var/lib/flynn/*.bolt ${BackupDir}
  ignore_errors: true
  
- name: Create flynn cluster with discovery peer-ips
  shell: flynn-host init --peer-ips {{ groups['flynn'] | join(',') }}
  notify: Restart flynn
  
- name: Make sure a service is running
  service:
    name: flynn-host
    state: started
#    enabled: yes

- name: Bootstrap cluster
  shell: CLUSTER_DOMAIN="{{ flynn_cluster_name }}" \
         flynn-host bootstrap \
         --min-hosts 3 \
         --peer-ips {{ groups['flynn'] | join(',') }}
  delegate_to: "{{ flynn_master }}"
  run_once: True
