- name: Get flynn install script
  get_url:
    url: https://dl.flynn.io/install-flynn
    dest: /opt/install-flynn
    mode: 0755
  environment: "{{ proxy_env }}"

- name: Check flynn
  shell: flynn-host --version
  ignore_errors: true
  when: {{ force }}
  register: is_flynn_installed

- name: Check if cluster was deployed
  shell: curl -I http://dashboard."{{ flynn_cluster_name }}"/
  ignore_errors: true
  register: is_flynn_deployed

- name: Install flynn
  shell: bash /opt/install-flynn
  when: is_flynn_installed|failed
  environment: "{{ proxy_env }}"

- name: Create flynn cluster with discovery peer-ips
  shell: flynn-host init --peer-ips {{ flynn_nodes | join('\n') }}
  notify: Restart flynn

- name: Make sure a service is running
  systemd:
    state: started
    name: flynn-host
    enabled: True

- name: Bootstrap cluster
  shell: CLUSTER_DOMAIN="{{ flynn_cluster_name }}" \
         flynn-host bootstrap \
         --min-hosts 3 \
         --peer-ips {{ flynn_nodes | join('\n') }}
  delegate_to: "{{ flynn_master }}"
  run_once: True
