---
- hosts: all
  become: true
  vars:
  
    flynn_cluster_name: flynn.cluster
    proxy_env:
      http_proxy: http://10.140.123.158:3128
      https_proxy: http://10.140.123.158:3128
      
    force: false
    
  roles:
    - init
    - flynn
