---
- hosts: all
  become: true
  gather_facts: no
  vars:
  
    flynn_master: 10.140.123.158
    flynn_cluster_name: flynn.cluster
    proxy_env:
      http_proxy: http://10.140.123.158:3128
      https_proxy: http://10.140.123.158:3128
      
    reboot: true
    reinstall: false
    
  roles:
    - init
    - flynn
