---
- hosts: all
  become: true
  vars:
    flynn_master: flynn01
    flynn_cluster_name: flynn.cluster
    proxy_env:
      http_proxy: 10.140.123.158:3128
      https_proxy: 10.140.123.158:3128
    force: false
  roles:
    - init
    - flynn
