---
# tasks file
- name: upload crts files to remote host
  copy:
    src: crts/
    dest: /root/crts/
    
- name: upload scripts to remote host
  copy:
    src: convert.sh
    dest: /root/convert.sh
  
- name: update ca certificates
  shell: bash convert.sh
